export const demoItems = [
  {
    id: "demo-leica-q3",
    name: "Leica Q3 Monochrom",
    brand: "Leica",
    category: "Tech",
    status: "owned",
    image: "/products/leica-q3.webp",
    purchasePrice: 6750,
    currentValue: 6900,
    targetPrice: "",
    purchaseDate: "2026-06-14",
    addedDate: "2026-05-02",
    retailer: "Leica Store",
    condition: "Excellent",
    warrantyUntil: "2028-06-14",
    location: "Bureau",
    priority: "",
    url: "https://leica-camera.com/en-GB/photography/cameras/q/q3-monochrom/shop-now",
    notes: "Boîte, chargeur et facture conservés",
  },
  {
    id: "demo-knob1",
    name: "Knob1",
    brand: "Work Louder",
    category: "Tech",
    status: "wishlist",
    image: "/products/knob1.webp",
    purchasePrice: "",
    currentValue: 445,
    targetPrice: 425,
    purchaseDate: "",
    addedDate: "2026-08-20",
    retailer: "Work Louder",
    condition: "Neuf",
    warrantyUntil: "",
    location: "",
    priority: "Haute",
    url: "https://worklouder.cc/knob1",
    notes: "Attendre le prochain restock européen",
  },
  {
    id: "demo-shower-head",
    name: "Shower Head+",
    brand: "Hello Klean",
    category: "Personnel",
    status: "owned",
    image: "/products/shower-head.webp",
    purchasePrice: 149,
    currentValue: 110,
    targetPrice: "",
    purchaseDate: "2026-02-07",
    addedDate: "2026-01-22",
    retailer: "Hello Klean",
    condition: "Très bon",
    warrantyUntil: "2028-02-07",
    location: "Salle de bain",
    priority: "",
    url: "https://helloklean.com/products/hello-klean-shower-head-plus",
    notes: "Changer la cartouche tous les quatre mois",
  },
  {
    id: "demo-pepper-mill",
    name: "P–1 Pepper Mill",
    brand: "Crust",
    category: "Maison",
    status: "wishlist",
    image: "/products/pepper-mill.png",
    purchasePrice: "",
    currentValue: 299,
    targetPrice: 260,
    purchaseDate: "",
    addedDate: "2026-08-12",
    retailer: "Crust",
    condition: "Neuf",
    warrantyUntil: "",
    location: "",
    priority: "Moyenne",
    url: "https://crustmill.com/",
    notes: "Coloris graphite",
  },
  {
    id: "demo-card-holder",
    name: "Card Holder 2.0",
    brand: "KILLSPENCER®",
    category: "Carry",
    status: "owned",
    image: "/products/card-holder.png",
    purchasePrice: 185,
    currentValue: 140,
    targetPrice: "",
    purchaseDate: "2025-11-04",
    addedDate: "2025-10-19",
    retailer: "KILLSPENCER®",
    condition: "Patiné",
    warrantyUntil: "",
    location: "EDC",
    priority: "",
    url: "https://killspencer.com/collections/wallet/products/card-holder-2-0",
    notes: "Cuir noir pleine fleur",
  },
  {
    id: "demo-beoplay",
    name: "Beoplay H100",
    brand: "Bang & Olufsen",
    category: "Tech",
    status: "wishlist",
    image: "/products/beoplay.png",
    purchasePrice: "",
    currentValue: 1499,
    targetPrice: 1250,
    purchaseDate: "",
    addedDate: "2026-07-28",
    retailer: "Bang & Olufsen",
    condition: "Neuf",
    warrantyUntil: "",
    location: "",
    priority: "Basse",
    url: "https://www.bang-olufsen.com/en/gb/headphones/beoplay-h100",
    notes: "Comparer au H95 avant achat",
  },
  {
    id: "demo-alessi-kettle",
    name: "Pulcina",
    brand: "Alessi",
    category: "Maison",
    status: "suggestion",
    image: "",
    purchasePrice: "",
    currentValue: 145,
    targetPrice: "",
    purchaseDate: "",
    addedDate: "2026-09-01",
    retailer: "Alessi",
    condition: "Neuf",
    warrantyUntil: "",
    location: "",
    priority: "Basse",
    url: "https://www.alessi.com/products/pulcina-mdl02",
    notes: "Idée cadeau — vu chez Marc, à revoir avant de le vouloir vraiment",
  },
  {
    id: "demo-nomos-club",
    name: "Club Campus 38",
    brand: "NOMOS Glashütte",
    category: "Carry",
    status: "suggestion",
    image: "",
    purchasePrice: "",
    currentValue: 1560,
    targetPrice: "",
    purchaseDate: "",
    addedDate: "2026-08-30",
    retailer: "NOMOS",
    condition: "Neuf",
    warrantyUntil: "",
    location: "",
    priority: "Basse",
    url: "https://nomos-glashuette.com/en/club/club-campus-38",
    notes: "À considérer un jour, pas une envie active",
  },
];

export const emptyItem = {
  name: "",
  brand: "",
  category: "",
  status: "wishlist",
  image: "",
  purchasePrice: "",
  currentValue: "",
  targetPrice: "",
  purchaseDate: "",
  addedDate: new Date().toISOString().slice(0, 10),
  retailer: "",
  condition: "Neuf",
  warrantyUntil: "",
  location: "",
  priority: "Moyenne",
  url: "",
  notes: "",
};
